// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyRentalManagement.Data;

#nullable disable

namespace PropertyRentalManagement.Migrations
{
    [DbContext(typeof(PRMDbContext))]
    [Migration("20241025235239_dataseed")]
    partial class dataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyRentalManagement.Models.Apartments", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentId"));

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ApartmentId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            ApartmentId = 1,
                            ApartmentNumber = "101",
                            BuildingId = 1,
                            ManagerId = 1,
                            Status = 1
                        },
                        new
                        {
                            ApartmentId = 2,
                            ApartmentNumber = "102",
                            BuildingId = 1,
                            ManagerId = 1,
                            Status = 0
                        },
                        new
                        {
                            ApartmentId = 3,
                            ApartmentNumber = "201",
                            BuildingId = 2,
                            ManagerId = 1,
                            Status = 1
                        },
                        new
                        {
                            ApartmentId = 4,
                            ApartmentNumber = "202",
                            BuildingId = 2,
                            ManagerId = 1,
                            Status = 2
                        },
                        new
                        {
                            ApartmentId = 5,
                            ApartmentNumber = "301",
                            BuildingId = 3,
                            ManagerId = 1,
                            Status = 1
                        },
                        new
                        {
                            ApartmentId = 6,
                            ApartmentNumber = "302",
                            BuildingId = 3,
                            ManagerId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Appointments", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TenantId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Buildings", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            Address = "123 Main St",
                            ManagerId = 1,
                            Name = "Sunset Apartments"
                        },
                        new
                        {
                            BuildingId = 2,
                            Address = "456 River Ave",
                            ManagerId = 1,
                            Name = "Riverfront Plaza"
                        },
                        new
                        {
                            BuildingId = 3,
                            Address = "789 Valley Rd",
                            ManagerId = 1,
                            Name = "Green Valley Towers"
                        });
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.EventReport", b =>
                {
                    b.Property<int>("EventReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventReportId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventReportId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TenantId");

                    b.ToTable("EventReports");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TenantId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.PropertyManager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ManagerId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UserId");

                    b.ToTable("PropertyManagers");

                    b.HasData(
                        new
                        {
                            ManagerId = 1,
                            Email = "manager1@example.com",
                            Name = "Jane Smith",
                            OwnerId = 1,
                            Phone = "555-555-5552",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.PropertyOwner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OwnerId");

                    b.HasIndex("UserId");

                    b.ToTable("PropertyOwners");

                    b.HasData(
                        new
                        {
                            OwnerId = 1,
                            Email = "owner1@example.com",
                            Name = "John Doe",
                            Phone = "555-555-5551",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<int?>("ApartmentsApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TenantId");

                    b.HasIndex("ApartmentsApartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UserId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            Email = "tenant1@example.com",
                            ManagerId = 1,
                            Name = "Michael Brown",
                            OwnerId = 1,
                            Phone = "555-555-5553",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "owner1@example.com",
                            Password = "pass123",
                            Phone = "555-555-5551",
                            Role = 0,
                            Username = "owner1"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "manager1@example.com",
                            Password = "pass123",
                            Phone = "555-555-5552",
                            Role = 1,
                            Username = "manager1"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "tenant1@example.com",
                            Password = "pass123",
                            Phone = "555-555-5553",
                            Role = 2,
                            Username = "tenant1"
                        });
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Apartments", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Buildings", "Building")
                        .WithMany("Apartments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.PropertyManager", "Manager")
                        .WithMany("Apartments")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Appointments", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Apartments", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.PropertyManager", "Manager")
                        .WithMany("Appointments")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.Tenant", "Tenant")
                        .WithMany("Appointments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Manager");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Buildings", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.PropertyManager", "Manager")
                        .WithMany("Buildings")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.EventReport", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.PropertyManager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Manager");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Message", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.PropertyManager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("PropertyRentalManagement.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Manager");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.PropertyManager", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.PropertyOwner", "Owner")
                        .WithMany("PropertyManagers")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.PropertyOwner", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Tenant", b =>
                {
                    b.HasOne("PropertyRentalManagement.Models.Apartments", null)
                        .WithMany("Tenants")
                        .HasForeignKey("ApartmentsApartmentId");

                    b.HasOne("PropertyRentalManagement.Models.PropertyManager", "Manager")
                        .WithMany("Tenants")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.PropertyOwner", "Owner")
                        .WithMany("Tenants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PropertyRentalManagement.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Owner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Apartments", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Buildings", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.PropertyManager", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Appointments");

                    b.Navigation("Buildings");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.PropertyOwner", b =>
                {
                    b.Navigation("PropertyManagers");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("PropertyRentalManagement.Models.Tenant", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
